### ISSUE TITLE
module can't start on server

### ISSUE THREAD

**Issue by shaikatzir** [leftshifters/excel-parser#11]
I used the module on my ubuntu laptop and it worked ok,
but when trying to run it on my ubuntu server I get:

TypeError: Object #<Object> has no method 'tmpDir'
    at Object.<anonymous> (/home/ubuntu/neo4jDonde/node_modules/excel-parser/node_modules/temp/lib/temp.js:142:32)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/ubuntu/neo4jDonde/node_modules/excel-parser/utils.js:6:12)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)

both machines are ubuntu 12.04 64 bit

**Comment by sthawali** [comment]
assuming its fixed @shaikatzir
